Repository woowa-techcamp-2020/bmart-8, pull requests merged in 2020-08, with the labels that each got.

#16 feat: 찜 버튼 컴포넌트 구현
  client/src/components/WishButton.tsx
Labels: front-end

#14 feat: 쇼핑카트 컴포넌트 코드 작성
  client/src/components/ShoppingCart.js
Labels: front-end

#18 style: footer 아이콘 추가
  client/package.json
  client/src/components/footer.tsx
Labels: styling

#22 Nohgijin/issue20
  client/src/components/Header.js
  client/src/components/Logo.js
  client/src/components/Search.js
  client/src/components/footer.tsx
  client/src/pages/MainPage.tsx
  client/src/static/icon/icon-backery.png
  client/src/static/icon/icon-fruit.png
  client/src/static/icon/icon-icecream.png
  client/src/static/icon/icon-living.png
  client/src/static/icon/icon-logo.png
  client/src/static/icon/icon-meal.png
  client/src/static/icon/icon-salad.png
  client/src/static/icon/icon-search.png
  client/src/static/icon/icon-vegi.png
Labels: front-end

#24 feat: 카테고리 API
  .github/workflows/client_build.yml
  .gitignore
  server/env.ts
  server/package.json
  server/prisma/schema.prisma
  server/src/entities/index.ts
  server/src/graphql/index.ts
  server/src/graphql/resolvers/category.ts
  server/src/graphql/schema.ts
  server/src/graphql/types/category.graphql
  server/src/index.ts
  server/src/server.ts
  server/yarn.lock
Labels: back-end

#32 refactor: Change file name, resolve warning
  client/src/App.tsx
  client/src/components/Header.tsx
  client/src/components/Logo.tsx
  client/src/components/PriceLabel.tsx
  client/src/components/Search.tsx
  client/src/components/ShoppingCart.tsx
  client/src/pages/CartPage.tsx
Labels: front-end

#38 feat: Create prisma user model
  server/prisma/schema.prisma
Labels: back-end

#41 Prisma Schema 작성
  server/prisma/.env.sample
  server/prisma/schema.prisma
  server/src/graphql/resolvers/category.ts
Labels: back-end

#51 서버 자동배포
  server/Dockerfile
  server/src/server.ts
Labels: back-end

#52 빌드스크립트 수정
  scripts/build_client.sh
  scripts/build_server.sh
Labels: bug

#56 카테고리 컴포넌트 제작
  client/src/App.tsx
  client/src/components/CategoryContent.js
  client/src/components/CategoryTitle.js
  client/src/lib/styles/palette.ts
  client/src/pages/CategoryPage.js
  client/src/pages/CategoryPage.tsx
  client/tsconfig.json
  server/prisma/.env.sample
Labels: front-end

#59 주문내역, 찜 컴포넌트 생성, second category 닫힘 이벤트
  client/src/components/ArrowBack.tsx
  client/src/components/ArrowFront.tsx
  client/src/components/category/CategoryContent.js
  client/src/components/category/CategoryTitle.js
  client/src/components/category/Dibs.js
  client/src/components/category/GoBmart.js
  client/src/components/category/OrderList.js
  client/src/lib/styles/palette.ts
  client/src/pages/CategoryPage.js
Labels: front-end

#62 Atobaum/issue39
  client/src/components/Carousel/Carousel.tsx
  client/src/components/Carousel/CarouselSelector.tsx
  client/src/components/Carousel/index.ts
  client/src/components/Header.tsx
  client/src/pages/MainPage.tsx
Labels: front-end

#64 Atobaum/issue45
  client/src/components/Carousel/CarouselSelector.tsx
  client/src/components/DeliveryAvailabilityIndicator.tsx
  client/src/components/MainPageCategories/CategoryIconButton.tsx
  client/src/components/MainPageCategories/MainPageCategories.tsx
  client/src/components/MainPageCategories/index.ts
  client/src/pages/MainPage.tsx
Labels: front-end

#67 캐로셀 타이밍 이슈 수정/ 리팩터
  client/src/components/Carousel/Carousel.tsx
  client/src/components/MainPageCategories/MainPageCategories.tsx
Labels: bug, front-end

#66 Pull to refresh 구현
  client/src/components/PullToRefresh.tsx
  client/src/pages/MainPage.tsx
  client/src/utils/addPointerEventHandlers.ts
  client/src/utils/index.ts
Labels: front-end

#70 메인페이지 상품 컴포넌트 생성
  client/src/components/ShoppingCart.tsx
  client/src/components/WishButton.tsx
  client/src/components/main/Product.js
  client/src/components/main/common/Bag.js
  client/src/components/main/common/ProductContent.js
  client/src/components/main/common/ProductInfo.js
  client/src/components/main/common/ProductPhoto.js
  client/src/components/main/common/Refresh.js
  client/src/components/main/discount/ProductDiscount.js
  client/src/components/main/discount/ProductFlashDiscount.js
  client/src/components/main/new/ProductNew.js
  client/src/components/main/nowEssential/ProductEssential.js
  client/src/components/main/readyFor/ProductReadyFor.js
  client/src/components/main/sellGood/ProductSellGood.js
  client/src/components/main/whatEat/ProductWhatEat.js
  client/src/pages/MainPage.tsx
Labels: front-end

#76 Feat/search
  client/package.json
  client/src/App.tsx
  client/src/components/Carousel/Carousel.tsx
  client/src/components/Footer.tsx
  client/src/components/Search.tsx
  client/src/components/Search/SearchHistoryItem.tsx
  client/src/components/Search/SearchInput.tsx
  client/src/components/Search/SearchRecommendationList.tsx
  client/src/hooks/useDebounce.ts
  client/src/pages/SearchPage.tsx
  client/src/pages/SearchResultPage.tsx
  client/yarn.lock
  server/src/graphql/resolvers/search.ts
  server/src/graphql/types/search.graphql
  server/src/server.ts
Labels: back-end, front-end

#77 Atobaum/issue36
  client/package.json
  client/src/pages/BookmarkPage.tsx
  client/src/pages/CartPage.tsx
  client/src/pages/CategoryPage.js
  client/src/pages/MainPage.tsx
  client/src/pages/ProductDetailPage.tsx
  client/src/pages/SearchPage.tsx
  client/src/pages/SearchResultPage.tsx
  client/src/pages/UserProfilePage.tsx
  client/yarn.lock
Labels: front-end

#78 메인페이지 스타일 수정
  client/package-lock.json
  client/src/App.tsx
  client/src/components/Footer.tsx
  client/src/components/Header.tsx
  client/src/components/WishButton.tsx
  client/src/components/main/Product.js
  client/src/components/main/common/ProductContent.js
  client/src/components/main/common/ProductInfo.js
  client/src/components/main/common/ProductPhoto.js
  client/src/components/main/common/Refresh.js
  client/src/components/main/nowEssential/ProductEssential.js
  client/src/components/main/whatEat/ProductWhatEat.js
  client/src/pages/MainPage.tsx
  client/yarn.lock
  server/package-lock.json
Labels: front-end, styling

#81 메인 페이지 캐로셀 더미 이미지 삭제, 땡겨요 스타일 수정
  README.md
  client/package-lock.json
  client/src/App.css
  client/src/App.tsx
  client/src/components/Carousel/Carousel.tsx
  client/src/components/Footer.tsx
  client/src/components/PullToRefresh.tsx
  client/src/components/Search/SearchInput.tsx
  client/src/hooks/useMainBanners.ts
  client/src/pages/CategoryPage.js
  client/src/pages/MainPage.tsx
  client/yarn.lock
  server/package-lock.json
  server/prisma/schema.prisma
  server/src/graphql/resolvers/banner.ts
  server/src/graphql/types/banner.graphql
  server/yarn.lock
Labels: back-end, front-end, styling

#93 상품컴포넌트 데이터베이스 연동
  client/src/components/category/CategoryContent.js
  client/src/components/main/discount/ProductDiscount.js
  client/src/components/main/discount/ProductFlashDiscount.js
  client/src/components/main/new/ProductNew.js
  client/src/components/main/nowEssential/ProductEssential.js
  client/src/components/main/readyFor/ProductReadyFor.js
  client/src/components/main/sellGood/ProductSellGood.js
  client/src/components/main/whatEat/ProductWhatEat.js
  client/src/utils/random.js
Labels: back-end, front-end

#96 땡겨요 리팩터, 버그 수정
  client/src/components/PullToRefresh.tsx
  client/src/components/main/common/ProductPhoto.js
  client/src/components/main/discount/ProductDiscount.js
  client/src/components/main/discount/ProductFlashDiscount.js
  client/src/hooks/useScrollDiff.ts
  client/src/pages/MainPage.tsx
  client/src/utils/addEventListenerEffect.ts
Labels: front-end

#103 chore: logo, seach-icon 추가
  client/public/icon/bmart-logo.png
  client/src/components/Logo.tsx
  client/src/components/Search.tsx
Labels: styling

#105 Nohgijin/issue101
  client/src/components/category/CategoryContent.js
  client/src/components/main/discount/ProductFlashDiscount.js
  client/src/components/main/new/ProductNew.js
  client/src/components/main/nowEssential/ProductEssential.js
  client/src/components/main/readyFor/ProductReadyFor.js
  client/src/components/main/sellGood/ProductSellGood.js
  client/src/components/main/whatEat/ProductWhatEat.js
  client/src/pages/CategoryPage.js
Labels: front-end

#106 chore: 오류 수정
  client/src/components/category/CategoryContent.js
Labels: front-end

#108 장바구니 페이지
  client/src/App.tsx
  client/src/components/Cart/CartHeader.tsx
  client/src/components/Cart/CartItem.tsx
  client/src/components/Cart/CartItemCounter.tsx
  client/src/components/Footer.tsx
  client/src/components/GoBackButton.tsx
  client/src/components/PullToRefresh.tsx
  client/src/components/Search/SearchInput.tsx
  client/src/components/main/Product.js
  client/src/components/main/common/ProductContent.js
  client/src/components/main/common/ProductInfo.js
  client/src/components/main/discount/ProductFlashDiscount.js
  client/src/components/main/new/ProductNew.js
  client/src/components/main/nowEssential/ProductEssential.js
  client/src/components/main/readyFor/ProductReadyFor.js
  client/src/components/main/sellGood/ProductSellGood.js
  client/src/components/main/whatEat/ProductWhatEat.js
  client/src/index.tsx
  client/src/pages/CartPage.tsx
  client/src/stores/cart-store.tsx
  client/src/utils/add-event-listener-effect.ts
  client/src/utils/addPointerEventHandlers.ts
  client/src/utils/index.ts
  server/package.json
  server/src/graphql/resolvers/cart.ts
  server/src/graphql/types/cart.graphql
  server/src/graphql/types/product.graphql
  server/src/server.ts
  server/yarn.lock
Labels: back-end, front-end

#120 상품 카테고리 클릭 시 화면
  client/src/App.tsx
  client/src/components/CategoryDetail/CategoryHeader.js
  client/src/components/CategoryDetail/CategoryProduct.js
  client/src/components/CategoryDetail/ProductHowAbout.js
  client/src/components/MainPageCategories/MainPageCategories.tsx
  client/src/components/category/CategoryContent.js
  client/src/components/main/discount/ProductFlashDiscount.js
  client/src/components/main/main-query.ts
  client/src/components/main/new/ProductNew.js
  client/src/components/main/nowEssential/ProductEssential.js
  client/src/components/main/readyFor/ProductReadyFor.js
  client/src/components/main/sellGood/ProductSellGood.js
  client/src/components/main/whatEat/ProductWhatEat.js
  client/src/pages/CategoryDetailPage.tsx
Labels: front-end

#126 카테고리 세부 페이지 추가
  client/package.json
  client/src/components/CategoryDetail/CategoryHeader.js
  client/src/components/CategoryDetail/CategoryProduct.js
  client/src/components/CategoryDetail/ThirdCategory.js
  client/src/components/category/CategoryContent.js
  client/src/components/main/readyFor/ProductReadyFor.js
  client/src/pages/CategoryPage.js
Labels: front-end

#122 JWT 유저 정보 수정
  client/src/index.tsx
  server/src/passportConfig.ts
Labels: back-end, front-end

#119 메인페이지 장바구니 버그/리팩터
  client/package.json
  client/src/components/Login/GoogleLoginBtn.tsx
  client/src/components/main/Category.js
  client/src/components/main/CategoryButton/CategoryIconButton.tsx
  client/src/components/main/CategoryButton/MainPageCategories.tsx
  client/src/components/main/CategoryButton/index.ts
  client/src/components/main/Product.js
  client/src/components/main/ProductCategory.js
  client/src/components/main/ProductEssential.tsx
  client/src/components/main/ProductFlashDiscount/ProductDiscount.js
  client/src/components/main/ProductFlashDiscount/ProductFlashDiscount.js
  client/src/components/main/ProductFlashDiscount/index.ts
  client/src/components/main/ProductNew.tsx
  client/src/components/main/ProductReadyFor.tsx
  client/src/components/main/ProductSellGood.tsx
  client/src/components/main/ProductWhatEat.tsx
  client/src/components/main/common/Refresh.tsx
  client/src/components/main/discount/ProductFlashDiscount.js
  client/src/components/main/hooks/useRandomProducts.tsx
  client/src/components/main/main-query.ts
  client/src/pages/MainPage.tsx
Labels: front-end, refactor

#135 feat: graphql 쿼리를 뭉쳐서 보내기
  client/package.json
  client/src/index.tsx
  client/yarn.lock
Labels: enhancement, front-end

#129 Server deploy
  .github/workflows/client_build.yml
  .github/workflows/server_build.yml
  client/appspec.yml
  client/scripts/before_client_deploy.sh
  server/Dockerfile
  server/appspec.yml
  server/package.json
  server/scripts/after_server_deploy.sh
  server/scripts/before_server_deploy.sh
  server/scripts/build_server.sh
  server/src/env.ts
  server/src/graphql/index.ts
  server/src/server.ts
  server/tsconfig.json
  server/yarn.lock
Labels: back-end

#134 feat: 더보기 url 연결 및 헤더 설정
  client/src/App.tsx
  client/src/components/CategoryDetail/CategoryHeader.js
  client/src/components/CategoryDetail/CategoryProduct.js
  client/src/pages/CategoryDetailPage.tsx
Labels: front-end

#141 Revert "fix: 빠진 폰트 추가"
  client/src/App.tsx
Labels: bug, front-end

#139 장바구니 수정, refresh부분 하는중
  client/src/components/CategoryDetail/CategoryHeader.js
  client/src/components/main/ProductEssential.tsx
  client/src/components/main/ProductFlashDiscount/ProductFlashDiscount.js
  client/src/components/main/ProductWhatEat.tsx
  client/src/components/main/common/ProductContent.js
  client/src/components/main/common/ProductInfo.js
  client/src/components/main/hooks/useLazyRandomEssential.tsx
  client/src/components/main/hooks/useLazyRandomProducts.tsx
Labels: front-end

#145 더보기 링크를 연결
  client/src/App.tsx
  client/src/components/Footer.tsx
  client/src/components/main/category/CategoryNavbar.tsx
  client/src/components/main/category/CategoryProductItem.tsx
  client/src/components/main/category/CategoryProductList.tsx
  client/src/components/main/common/ProductInfo.js
Labels: front-end

#147 할인률 표시
  client/src/components/CategoryDetail/CategoryProduct.js
  client/src/components/PriceLabel.tsx
  client/src/components/main/ProductEssential.tsx
  client/src/components/main/ProductFlashDiscount/ProductFlashDiscount.js
  client/src/components/main/ProductNew.tsx
  client/src/components/main/ProductReadyFor.tsx
  client/src/components/main/ProductSellGood.tsx
  client/src/components/main/ProductWhatEat.tsx
  client/src/components/main/category/CategoryProductItem.tsx
  client/src/components/main/common/ProductContent.js
  client/src/components/main/common/ProductInfo.js
  client/src/pages/SearchResultPage.tsx
Labels: front-end
